// <auto-generated />
using System;
using DataLabeling.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataLabeling.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260318075103_AddFieldLabel")]
    partial class AddFieldLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("ItemId");

                    b.HasIndex("DatasetId");

                    b.ToTable("data_items", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.Annotation", b =>
                {
                    b.Property<int>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("annotation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnotationId"));

                    b.Property<int>("AnnotatorId")
                        .HasColumnType("integer");

                    b.Property<string>("Classification")
                        .HasColumnType("text");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("coordinates");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("LabelId")
                        .HasColumnType("integer")
                        .HasColumnName("label_id");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("shape_type");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("AnnotationId");

                    b.HasIndex("AnnotatorId");

                    b.HasIndex("ItemId");

                    b.HasIndex("LabelId");

                    b.HasIndex("TaskId");

                    b.ToTable("annotations", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.Dataset", b =>
                {
                    b.Property<int>("DatasetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("dataset_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DatasetId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DatasetName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("dataset_name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("DatasetId");

                    b.HasIndex("ProjectId");

                    b.ToTable("datasets", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.DatasetRound", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoundId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DatasetId")
                        .HasColumnType("integer")
                        .HasColumnName("dataset_id");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<int>("ShapeType")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("RoundId");

                    b.HasIndex("DatasetId");

                    b.ToTable("dataset_rounds", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("label_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LabelId"));

                    b.Property<int?>("AnnotatorId")
                        .HasColumnType("integer")
                        .HasColumnName("annotator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("label_name");

                    b.Property<int>("LabelStatus")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("label_status");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LabelId");

                    b.HasIndex("AnnotatorId");

                    b.HasIndex("RoundId");

                    b.HasIndex("UserId");

                    b.ToTable("labels", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ManagerId")
                        .HasColumnType("integer")
                        .HasColumnName("manager_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("ProjectId");

                    b.HasIndex("ManagerId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime?>("AnnotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("annotated_at");

                    b.Property<int?>("AnnotatorId")
                        .HasColumnType("integer")
                        .HasColumnName("annotator_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DataItemId")
                        .HasColumnType("integer")
                        .HasColumnName("data_item_id");

                    b.Property<string>("DescriptionError")
                        .HasColumnType("text")
                        .HasColumnName("description_error");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("TaskId");

                    b.HasIndex("AnnotatorId");

                    b.HasIndex("DataItemId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("RoundId");

                    b.HasIndex("UserId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.TaskErrorHistory", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("error_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ErrorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DataItemItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer")
                        .HasColumnName("reviewer_id");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ErrorId");

                    b.HasIndex("DataItemItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("task_error_histories", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("token_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Expired")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_type");

                    b.Property<string>("TokenValue")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("UserId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("DataLabeling.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DataItem", b =>
                {
                    b.HasOne("DataLabeling.Entities.Dataset", "Dataset")
                        .WithMany("DataItems")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("DataLabeling.Entities.Annotation", b =>
                {
                    b.HasOne("DataLabeling.Entities.User", "Annotator")
                        .WithMany()
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataItem", "DataItem")
                        .WithMany("Annotations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabeling.Entities.Label", "Label")
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabeling.Entities.Task", "Task")
                        .WithMany("Annotations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Annotator");

                    b.Navigation("DataItem");

                    b.Navigation("Label");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DataLabeling.Entities.Dataset", b =>
                {
                    b.HasOne("DataLabeling.Entities.Project", "Project")
                        .WithMany("Datasets")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DataLabeling.Entities.DatasetRound", b =>
                {
                    b.HasOne("DataLabeling.Entities.Dataset", "Dataset")
                        .WithMany("Rounds")
                        .HasForeignKey("DatasetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("DataLabeling.Entities.Label", b =>
                {
                    b.HasOne("DataLabeling.Entities.User", "Annotator")
                        .WithMany()
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataLabeling.Entities.DatasetRound", "Round")
                        .WithMany("Labels")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabeling.Entities.User", null)
                        .WithMany("CreatedLabels")
                        .HasForeignKey("UserId");

                    b.Navigation("Annotator");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DataLabeling.Entities.Project", b =>
                {
                    b.HasOne("DataLabeling.Entities.User", "Manager")
                        .WithMany("Projects")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("DataLabeling.Entities.Task", b =>
                {
                    b.HasOne("DataLabeling.Entities.User", "Annotator")
                        .WithMany()
                        .HasForeignKey("AnnotatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataItem", "DataItem")
                        .WithMany("Tasks")
                        .HasForeignKey("DataItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabeling.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataLabeling.Entities.DatasetRound", "Round")
                        .WithMany("Tasks")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataLabeling.Entities.User", null)
                        .WithMany("AssignedTasks")
                        .HasForeignKey("UserId");

                    b.Navigation("Annotator");

                    b.Navigation("DataItem");

                    b.Navigation("Reviewer");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("DataLabeling.Entities.TaskErrorHistory", b =>
                {
                    b.HasOne("DataItem", null)
                        .WithMany("ErrorHistories")
                        .HasForeignKey("DataItemItemId");

                    b.HasOne("DataItem", "DataItem")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_error_histories_data_items");

                    b.HasOne("DataLabeling.Entities.User", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_error_histories_users");

                    b.HasOne("DataLabeling.Entities.Task", "Task")
                        .WithMany("ErrorHistories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_error_histories_tasks");

                    b.HasOne("DataLabeling.Entities.User", null)
                        .WithMany("ReviewedErrors")
                        .HasForeignKey("UserId");

                    b.Navigation("DataItem");

                    b.Navigation("Reviewer");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DataLabeling.Entities.Token", b =>
                {
                    b.HasOne("DataLabeling.Entities.User", "User")
                        .WithMany("Token")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataItem", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("ErrorHistories");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DataLabeling.Entities.Dataset", b =>
                {
                    b.Navigation("DataItems");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("DataLabeling.Entities.DatasetRound", b =>
                {
                    b.Navigation("Labels");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("DataLabeling.Entities.Project", b =>
                {
                    b.Navigation("Datasets");
                });

            modelBuilder.Entity("DataLabeling.Entities.Task", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("ErrorHistories");
                });

            modelBuilder.Entity("DataLabeling.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedLabels");

                    b.Navigation("Projects");

                    b.Navigation("ReviewedErrors");

                    b.Navigation("Token");
                });
#pragma warning restore 612, 618
        }
    }
}
